name:                psfmt
version:             0.2.1
github:              "reactormonk/psfmt"
license:             BSD3
author:              "Simon Hafner"
maintainer:          "hafnersimon@gmail.com"
copyright:           "LGPLv3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/reactormonk/psfmt#readme>

dependencies:
- base >= 4.7 && < 5
- text
- filepath
- generic-lens
- relude
- lens
- directory
- pathwalk
- purescript

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - NoImplicitPrelude

library:
  source-dirs: src

executables:
  psfmt:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -j4 +RTS -A32m -RTS
    - -optl=-pthread
    - -optc-Os
    - -fPIC
    - -optP-Wno-nonportable-include-path
    dependencies:
    - psfmt

tests:
  psfmt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -j4 +RTS -A32m -RTS
    - -optP-Wno-nonportable-include-path
    dependencies:
    - psfmt
    - tasty
    - tasty-golden
    - pretty-simple
